server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project?autoReconnect=true&useUnicode=true&serverTimezone=UTC
    username: root
    password: root

  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  output:
    ansi:
      enabled: always

